POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4MWEwYzI1MWE4NmZhOWU4MDc3ODQzNSIsImlhdCI6MTc0Njg4Mjc0NH0.kl9ktusCYEGtpIZXdwcR1Z9wXMEJdO2wZqcc573v1Aw

{
    "title": "Test delete3",
    "author": "Test Author1212",
    "url": "https://test.com1212",
    "likes": 1011
}